export const ErrorCodes = {
  E_UNAUTHORIZED: 'E_UNAUTHORIZED',
  E_FORBIDDEN: 'E_FORBIDDEN',
  E_USER_NOT_FOUND: 'E_USER_NOT_FOUND',
  E_USER_ALREADY_EXISTS: 'E_USER_ALREADY_EXISTS',
  E_INVALID_CREDENTIALS: 'E_INVALID_CREDENTIALS',
  E_TOKEN_EXPIRED: 'E_TOKEN_EXPIRED',
  E_INVALID_TOKEN: 'E_INVALID_TOKEN',
  E_ACCOUNT_DEACTIVATED: 'E_ACCOUNT_DEACTIVATED',
  E_VALIDATION_ERROR: 'E_VALIDATION_ERROR',
  E_INTERNAL_SERVER_ERROR: 'E_INTERNAL_SERVER_ERROR',
  E_ORDER_STATE_INVALID: 'E_ORDER_STATE_INVALID',
  E_IDEMPOTENCY_CONFLICT: 'E_IDEMPOTENCY_CONFLICT',
  E_INSUFFICIENT_STOCK: 'E_INSUFFICIENT_STOCK',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
